### PR TITLE
PSR-2 conversion & Docblock enrichment

### PR DESCRIPTION
**Pull request by cedricziel**
Converting to PSR-2 is a reasonable choice since it's the de-facto coding standard in the PHP community.

The minor tweaks to the standard in the `.php_cs` config file are heavily inspired by the symfony and TYPO3 CMS coding standards. Adding the `.php_cs` config file allows for reproducable code-style conversion.

While on the task I added / corrected docblocks wherever possible.

Closes: #40

### CODE REVIEW

**Comment by tbetbetbe** [comment]
LGTM - thank you very much !

FYI: @bshaffer, @stanley-cheung, can you take look as well ?

**Comment by tbetbetbe** [comment]
@bshaffer, @stanley-cheung: I will wait another day before taking silence to mean that you are OK with this change.

**Comment by stanley-cheung** [comment]
LGTM, sorry for the delay. I saw this a couple of days ago. Didn't know you can specify `.editorconfig` and `.php_cs`. Neat! PSR-2 is great, we also used this in the grpc repo.

**Comment by bshaffer** [comment]
This is great. `.editorconfig` is used by most of the big OS projects, so I'm cool with it. I've experienced several issues with `php-cs-fixer` (mostly whitespace-related), so we'll want to keep an eye on that.

**Comment by cedricziel** [comment]
Cool - so all that's missing is a merge :)

**Pull request merged**
