### PR TITLE
Fix bug when merging headers on Guzzle5 http handler

### PR DESCRIPTION
**Pull request by erictinocopro**
This will avoid removing already set headers with headers from options (like encryption)

### CODE REVIEW

**Comment by erictinocopro** [comment]
I signed it!

**Comment by erictinocopro** [comment]
I signed it!

**Comment by bshaffer** [comment]
@erictinocopro thank you for this, but as we have not tagged `1.2.1` yet, please remove your entry to the CHANGELOG and I will add it when we tag a new version.

Also, it would be great to have a test!

**Comment by bshaffer** [comment]
See #186

**Pull request closed without merging**
